[package]
name = "clash"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/clash.rs"

[dependencies]
clap = { version = "4.4.6", features = ["derive", "cargo"] }
directories = "5.0"
anyhow = "1.0.75"
rand = "0.8.5"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
shlex = "1.2.0"
regex = "1"
reqwest = { version = "0.11.22", features = ["blocking"] }
