unstable_features = true
max_width = 110
fn_call_width = 85
attr_fn_like_width = 85
chain_width = 85
imports_granularity = "Module"
group_imports = "StdExternalCrate"
trailing_semicolon = false
wrap_comments = true
