name = "c"
source_file_ext = "c"

[type_tokens]
Int = "int"
Long = "long long"
Float = "float"
Bool = "int"
String = "char"
Word = "char"

[variable_name_options]
casing = "snake_case"
allow_uppercase_vars = false
# TODO
keywords = [
  "for" 
]
