name = "cpp"
source_file_ext = "cpp"

[type_tokens]
Int = "int"
Long = "long long"
Float = "float"
Bool = "int"
String = "string"
Word = "string"

[variable_name_options]
casing = "snake_case"
allow_uppercase_vars = false
keywords = [
  "auto", "break", "case", "char",
  "const", "continue", "default", "do",
  "double", "else", "enum", "extern",
  "float", "for", "goto", "if", "int",
  "long", "new", "operator", "register", "return",
  "short", "signed", "sizeof", "static", "string",
  "struct", "switch", "template", "typedef", "union",
  "unsigned", "void", "volatile", "while"
]
