name = "python"
source_file_ext = "py"

[type_tokens]
Int = "int"
Long = "int"
Float = "float"
Bool = " != \"0\""
String = "UNUSED"
Word = "UNUSED"

[variable_name_options]
casing = "snake_case"
allow_uppercase_vars = false
keywords = [
    # https://docs.python.org/3/reference/lexical_analysis.html#keywords
    "False", "await", "else", "import", "pass",
    "None", "break", "except", "in", "raise",
    "True", "class", "finally", "is", "return",
    "and", "continue", "for", "lambda", "try",
    "as", "def", "from", "nonlocal", "while",
    "assert", "del", "global", "not", "with",
    "async", "elif", "if", "or", "yield",
]
