on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          TOOLCHAIN_VERSION: stable
  publish:
    name: publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: taiki-e/install-action@cargo-hack
      - name: Check minimum supported Rust version (MSRV)
        run: cargo hack check --rust-version --workspace --all-targets --ignore-private
      - name: Publish on crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
